const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const cli = path.resolve(__dirname, '../bin/fde.js')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-masking-'))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const env = { ...process.env, HOME: dir, USERPROFILE: dir, FDEOPS_ENGAGEMENT: '', FDEOS_ENGAGEMENT: '', FDEOPS_ENGAGEMENTS_ROOT: path.join(dir, 'clients') }
  const run = args => spawnSync(process.execPath, [cli, ...args], { cwd: dir, env, encoding: 'utf8' })
  assert.equal(run(['resume', '--init', 'atlas']).status, 0)
  return { dir, env, run, eng: path.join(dir, 'clients/atlas/.fde') }
}
test('default context masks identifiers consistently without changing records', t => {
  const f = fixture(t), p = path.join(f.eng, 'context.md')
  const original = '# Context\n## Next action\nContact mara@example.com at +1 415 555 0123. ID 123-45-6789. Due 2026-09-15; target 99.9%.\n<private>HIDDEN_PERSON</private>\n'
  fs.writeFileSync(p, original)
  const first = f.run(['resume']), second = f.run(['resume'])
  assert.equal(first.status, 0, first.stderr)
  assert.doesNotMatch(first.stdout + first.stderr, /mara@example.com|415 555 0123|123-45-6789|HIDDEN_PERSON/)
  assert.match(first.stdout, /2026-09-15/)
  assert.match(first.stdout, /99\.9%/)
  const alias = first.stdout.match(/\[\[email:[a-f0-9]{16}\]\]/)[0]
  assert.ok(second.stdout.includes(alias))
  assert.equal(fs.readFileSync(p, 'utf8'), original)
  assert.ok(f.run(['recall', alias]).stdout.includes(alias))
})
test('masked proposal can be edited and applied with original identifiers and sources', t => {
  const f = fixture(t), notes = path.join(f.dir, 'notes.md')
  fs.writeFileSync(notes, 'decision: Ask mara@example.com for staging access. [source: mail:mara@example.com]\n<private>HIDDEN_PERSON</private>\n')
  const preview = f.run(['debrief', '--smart', notes])
  assert.equal(preview.status, 0, preview.stderr)
  const p = path.join(f.eng, '.debrief-propose'), proposal = fs.readFileSync(p, 'utf8')
  assert.doesNotMatch(preview.stdout + proposal, /mara@example.com|HIDDEN_PERSON/)
  assert.match(proposal, /\[\[email:[a-f0-9]{16}\]\]/)
  fs.writeFileSync(p, proposal.replace('staging access', 'staging access on Tuesday'))
  const applied = f.run(['debrief', '--apply'])
  assert.equal(applied.status, 0, applied.stderr)
  assert.doesNotMatch(applied.stdout + applied.stderr, /mara@example.com|HIDDEN_PERSON/)
  assert.match(fs.readFileSync(path.join(f.eng, 'decisions.md'), 'utf8'), /Ask mara@example.com for staging access on Tuesday\. \[source: mail:mara@example.com\]/)
  assert.match(fs.readFileSync(path.join(f.eng, 'context.md'), 'utf8'), /HIDDEN_PERSON/)
})
test('missing alias map refuses an apply instead of saving aliases', t => {
  const f = fixture(t), notes = path.join(f.dir, 'notes.md')
  fs.writeFileSync(notes, 'decision: Contact mara@example.com.\n')
  assert.equal(f.run(['debrief', '--smart', notes]).status, 0)
  const before = fs.readFileSync(path.join(f.eng, 'decisions.md'))
  fs.rmSync(path.join(f.dir, 'clients/.privacy'), { recursive: true, force: true })
  const result = f.run(['debrief', '--apply'])
  assert.notEqual(result.status, 0)
  assert.deepEqual(fs.readFileSync(path.join(f.eng, 'decisions.md')), before)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example.com/)
})
test('private map rejects links and corrupt state without leaking identifiers', t => {
  const f = fixture(t), p = path.join(f.eng, 'context.md')
  fs.writeFileSync(p, '# Context\nContact mara@example.com\n')
  const outside = path.join(f.dir, 'outside'); fs.mkdirSync(outside)
  fs.symlinkSync(outside, path.join(f.dir, 'clients/.privacy'))
  let result = f.run(['resume'])
  assert.notEqual(result.status, 0)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example.com/)
  assert.deepEqual(fs.readdirSync(outside), [])
  fs.unlinkSync(path.join(f.dir, 'clients/.privacy'))
  assert.equal(f.run(['resume']).status, 0)
  fs.writeFileSync(path.join(f.dir, 'clients/.privacy/identifiers.json'), '{broken private value mara@example.com')
  result = f.run(['resume'])
  assert.notEqual(result.status, 0)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example.com/)
})
test('masking preserves context byte budget and protects stderr', t => {
  const f = fixture(t)
  fs.writeFileSync(path.join(f.eng, 'context.md'), '# Context\n' + 'a@b.co '.repeat(4000))
  const output = f.run(['resume', '--max-bytes', '4096'])
  assert.equal(output.status, 0, output.stderr)
  assert.ok(Buffer.byteLength(output.stdout) <= 4096)
  assert.doesNotMatch(output.stdout, /a@b.co/)
  const error = f.run(['debrief', path.join(f.dir, 'mara@example.com.txt')])
  assert.doesNotMatch(error.stdout + error.stderr, /mara@example.com/)
})
test('private identifiers map stays outside engagement history', t => {
  const f = fixture(t), notes = path.join(f.dir, 'notes.md')
  fs.writeFileSync(notes, 'decision: Contact mara@example.com.\n')
  assert.equal(f.run(['debrief', '--smart', notes]).status, 0)
  assert.equal(f.run(['debrief', '--apply']).status, 0)
  const tracked = spawnSync('git', ['ls-files'], { cwd: f.eng, encoding: 'utf8' }).stdout
  assert.doesNotMatch(tracked, /privacy|identifiers/)
  if (process.platform !== 'win32') assert.equal(fs.statSync(path.join(f.dir, 'clients/.privacy/identifiers.json')).mode & 0o777, 0o600)
})
test('clipped summaries mask complete identifiers before shortening', t => {
  const f = fixture(t)
  fs.writeFileSync(path.join(f.eng, 'success.md'), '# Success\n' + 'x'.repeat(145) + ' mara@example.com\n')
  const result = f.run(['prep'])
  assert.equal(result.status, 0, result.stderr)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@/)
})
test('filesystem exceptions pass through masking instead of Node raw stacks', t => {
  const f = fixture(t), inbox = path.join(f.dir, 'clients/atlas/.inbox')
  fs.mkdirSync(inbox)
  fs.symlinkSync(path.join(f.dir, 'missing'), path.join(inbox, 'mara@example.com.md'))
  const result = f.run(['ingest', 'list'])
  assert.notEqual(result.status, 0)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example/)
})
test('MCP responses mask identifiers before crossing the tool boundary', t => {
  const f = fixture(t)
  const server = path.resolve(__dirname, '../mcp/fdeops-ingest/server.js')
  const request = { jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'unknown-mara@example.com', arguments: {} } }
  const result = spawnSync(process.execPath, [server], { cwd: f.dir, env: f.env, input: JSON.stringify(request) + '\n', encoding: 'utf8', timeout: 5000 })
  assert.equal(result.status, 0, result.stderr)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example/)
  assert.match(result.stdout, /email:/)
})
test('output protection handles split writes and multiline credentials', t => {
  const f = fixture(t), modulePath = path.resolve(__dirname, '../bin/lib/masking.js')
  const script = `const m=require(${JSON.stringify(modulePath)});m.protectOutput(m.createMasking(${JSON.stringify(path.join(f.dir, 'clients'))}));process.stdout.write('mara@');process.stdout.write('example.com');process.stderr.write('-----BEGIN PRIVATE KEY-----\\nSECRET_BODY\\n-----END PRIVATE KEY-----');`
  const result = spawnSync(process.execPath, ['-e', script], { env: f.env, encoding: 'utf8' })
  assert.equal(result.status, 0, result.stderr)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@|example.com|SECRET_BODY/)
})
test('unknown alias fails closed before a record write', t => {
  const f = fixture(t), p = path.join(f.eng, 'decisions.md'), before = fs.readFileSync(p)
  const result = f.run(['log', 'decision', 'Contact [[email:0123456789abcdef]]'])
  assert.notEqual(result.status, 0)
  assert.deepEqual(fs.readFileSync(p), before)
})
test('identifier discovery remains bounded on long non-identifier text', t => {
  const f = fixture(t), modulePath = path.resolve(__dirname, '../bin/lib/masking.js')
  const script = `const m=require(${JSON.stringify(modulePath)}).createMasking(${JSON.stringify(path.join(f.dir, 'clients'))});m.mask('x'.repeat(1200000));`
  const result = spawnSync(process.execPath, ['-e', script], { env: f.env, encoding: 'utf8', timeout: 3000 })
  assert.equal(result.status, 0, String(result.error || result.stderr))
})
test('sourced replay still detects originals behind masked proposal aliases', t => {
  const f = fixture(t), notes = path.join(f.dir, 'notes.md')
  fs.writeFileSync(notes, 'decision: Contact mara@example.com. [source: mail-42]\n')
  assert.equal(f.run(['debrief', '--smart', notes]).status, 0)
  assert.equal(f.run(['debrief', '--apply']).status, 0)
  const again = f.run(['debrief', '--smart', notes])
  assert.match(again.stdout, /REPLAY WARNING/)
  const before = fs.readFileSync(path.join(f.eng, 'decisions.md'))
  assert.notEqual(f.run(['debrief', '--apply']).status, 0)
  assert.deepEqual(fs.readFileSync(path.join(f.eng, 'decisions.md')), before)
})
test('review masks a legacy proposal before an agent opens it', t => {
  const f = fixture(t), p = path.join(f.eng, '.debrief-propose')
  fs.writeFileSync(p, 'decision: Contact mara@example.com.\n')
  assert.equal(f.run(['debrief', '--review']).status, 0)
  assert.doesNotMatch(fs.readFileSync(p, 'utf8'), /mara@example/)
})
test('legacy inline-private proposals refuse review rather than signal safe file access', t => {
  const f = fixture(t), p = path.join(f.eng, '.debrief-propose')
  const original = 'decision: Contact mara@example.com\n<private>SECRET PRIVATE NOTE</private>\n'
  fs.writeFileSync(p, original)
  const result = f.run(['debrief', '--review'])
  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /do not open it with an agent/)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example|SECRET PRIVATE NOTE/)
  assert.equal(fs.readFileSync(p, 'utf8'), original)
})
test('alias dictionary file links are refused without reading their targets', t => {
  const f = fixture(t), context = path.join(f.eng, 'context.md')
  fs.writeFileSync(context, '# Context\nContact mara@example.com\n')
  assert.equal(f.run(['resume']).status, 0)
  const map = path.join(f.dir, 'clients/.privacy/identifiers.json'), outside = path.join(f.dir, 'outside.json')
  fs.writeFileSync(outside, 'PRIVATE_FILE_TARGET')
  fs.unlinkSync(map); fs.symlinkSync(outside, map)
  const result = f.run(['resume'])
  assert.notEqual(result.status, 0)
  assert.doesNotMatch(result.stdout + result.stderr, /mara@example|PRIVATE_FILE_TARGET/)
})
test('runtime exposes masking capability without revealing private state', t => {
  const f = fixture(t), result = f.run(['privacy'])
  assert.equal(result.status, 0)
  assert.match(result.stdout, /identifier masking enabled by default/)
  assert.match(result.stdout, /Names and arbitrary sensitive prose are not detected/)
  assert.equal(fs.existsSync(path.join(f.dir, 'clients/.privacy')), false)
})
