const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const cli = path.join(__dirname, '../bin/fde.js')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-budget-'))
  const eng = path.join(dir, 'client', '.fde')
  fs.mkdirSync(eng, { recursive: true })
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const run = args => spawnSync(process.execPath, [cli, ...args], { cwd: dir, env: { ...process.env, HOME: dir, FDEOPS_ENGAGEMENT: eng, FDEOPS_ENGAGEMENTS_ROOT: dir }, encoding: 'utf8' })
  return { dir, eng, run, write: (name, text) => fs.writeFileSync(path.join(eng, name), text) }
}
test('resume bounds a million-character line and clearly reports omitted content', t => {
  const f = fixture(t)
  f.write('context.md', '# Context\n**Phase:** land\n## Next action\nConfirm access\n' + 'X'.repeat(1000000))
  const out = f.run(['resume'])
  assert.equal(out.status, 0, out.stderr)
  assert.ok(Buffer.byteLength(out.stdout) <= 16384)
  assert.match(out.stdout, /Confirm access/)
  assert.match(out.stdout, /omitted|truncated/i)
  assert.match(out.stdout, /recall/)
})
test('recall retrieves older evidence with a source within its budget, scoped to this client', t => {
  const f = fixture(t)
  f.write('decisions.md', '# Decisions\n- [2026-01-01] retry MUST preserve idempotency. SOURCE_A\n\n' + 'unrelated '.repeat(60000) + '\n\n- [2026-09-10] retry scope changed; prior UI plan superseded. SOURCE_B\n<private>retry SECRET_SENTINEL</private>')
  const other = path.join(f.dir, 'other', '.fde'); fs.mkdirSync(other, { recursive: true }); fs.writeFileSync(path.join(other, 'decisions.md'), 'retry OTHER_CLIENT_SECRET')
  const out = f.run(['recall', 'retry', '--max-bytes', '4096'])
  assert.equal(out.status, 0, out.stderr)
  assert.ok(Buffer.byteLength(out.stdout) <= 4096)
  assert.match(out.stdout, /SOURCE_A/); assert.match(out.stdout, /SOURCE_B/)
  assert.match(out.stdout, /decisions.md/)
  assert.doesNotMatch(out.stdout, /SECRET_SENTINEL|OTHER_CLIENT_SECRET/)
  assert.match(out.stdout, /not.*approval|not.*acceptance|verify/i)
})
test('context budget validates options and preserves valid Unicode', t => {
  const f = fixture(t); f.write('context.md', '# Context\n' + '客户🙂'.repeat(10000))
  for (const args of [['resume', '--max-bytes', 'NaN'], ['recall', 'x', '--max-bytes', '0']]) assert.notEqual(f.run(args).status, 0)
  const out = f.run(['resume', '--max-bytes', '4096'])
  assert.equal(out.status, 0, out.stderr); assert.ok(Buffer.byteLength(out.stdout) <= 4096); assert.ok(!out.stdout.includes('\uFFFD'))
})
test('recall distinguishes an empty search from missing evidence and rejects raw-path queries as paths', t => {
  const f = fixture(t); f.write('context.md', '# Context\n')
  assert.notEqual(f.run(['recall']).status, 0)
  const out = f.run(['recall', '../other'])
  assert.equal(out.status, 0); assert.match(out.stdout, /no match|no matching/i)
})
test('entry and recall include sanitized policy; heading matches retain nearby denials', t => {
  const f = fixture(t)
  f.write('trust-profile.md', '# Policy\nOnly local models may read source code.\n<private>HIDDEN_POLICY_NOTE</private>')
  f.write('decisions.md', '## Retry approval\nThe sponsor explicitly denied production deployment.\n')
  const entry = f.run(['resume'])
  assert.match(entry.stdout, /Only local models/)
  const policy = f.run(['recall', 'local models'])
  assert.match(policy.stdout, /Only local models/); assert.doesNotMatch(policy.stdout, /HIDDEN_POLICY_NOTE/)
  const decision = f.run(['recall', 'retry approval'])
  assert.match(decision.stdout, /denied production deployment/)
})
test('recall retains recent changes and old constraints when a topic has many matches', t => {
  const f = fixture(t)
  f.write('decisions.md', '- [2026-01-01] retry MUST preserve idempotency. ORIGINAL_CONSTRAINT\n' + Array.from({ length: 50 }, (_, i) => `- retry checkpoint ${i}`).join('\n') + '\n- [2026-09-10] retry approval revoked. LATEST_REVOCATION\n')
  const out = f.run(['recall', 'retry'])
  assert.equal(out.status, 0)
  assert.match(out.stdout, /ORIGINAL_CONSTRAINT/); assert.match(out.stdout, /LATEST_REVOCATION/)
  assert.match(out.stdout, /of 52 matching/)
})
