const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const cli = path.join(__dirname, '../bin/fde.js')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-budget-'))
  const eng = path.join(dir, 'client', '.fde')
  fs.mkdirSync(eng, { recursive: true })
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const run = args => spawnSync(process.execPath, [cli, ...args], { cwd: dir, env: { ...process.env, HOME: dir, FDEOPS_ENGAGEMENT: eng, FDEOPS_ENGAGEMENTS_ROOT: dir }, encoding: 'utf8' })
  return { dir, eng, run, write: (name, text) => fs.writeFileSync(path.join(eng, name), text) }
}
test('resume bounds a million-character line and clearly reports omitted content', t => {
  const f = fixture(t)
  f.write('context.md', '# Context\n**Phase:** land\n## Next action\nConfirm access\n' + 'X'.repeat(1000000))
  const out = f.run(['resume'])
  assert.equal(out.status, 0, out.stderr)
  assert.ok(Buffer.byteLength(out.stdout) <= 16384)
  assert.match(out.stdout, /Confirm access/)
  assert.match(out.stdout, /omitted|truncated/i)
  assert.match(out.stdout, /recall/)
})
test('recall retrieves older evidence with a source within its budget, scoped to this client', t => {
  const f = fixture(t)
  f.write('decisions.md', '# Decisions\n- [2026-01-01] retry MUST preserve idempotency. SOURCE_A\n\n' + 'unrelated '.repeat(60000) + '\n\n- [2026-09-10] retry scope changed; prior UI plan superseded. SOURCE_B\n<private>retry SECRET_SENTINEL</private>')
  const other = path.join(f.dir, 'other', '.fde'); fs.mkdirSync(other, { recursive: true }); fs.writeFileSync(path.join(other, 'decisions.md'), 'retry OTHER_CLIENT_SECRET')
  const out = f.run(['recall', 'retry', '--max-bytes', '4096'])
  assert.equal(out.status, 0, out.stderr)
  assert.ok(Buffer.byteLength(out.stdout) <= 4096)
  assert.match(out.stdout, /SOURCE_A/); assert.match(out.stdout, /SOURCE_B/)
  assert.match(out.stdout, /decisions.md/)
  assert.doesNotMatch(out.stdout, /SECRET_SENTINEL|OTHER_CLIENT_SECRET/)
  assert.match(out.stdout, /not.*approval|not.*acceptance|verify/i)
})
test('context budget validates options and preserves valid Unicode', t => {
  const f = fixture(t); f.write('context.md', '# Context\n' + '客户🙂'.repeat(10000))
  for (const args of [['resume', '--max-bytes', 'NaN'], ['recall', 'x', '--max-bytes', '0']]) assert.notEqual(f.run(args).status, 0)
  const out = f.run(['resume', '--max-bytes', '4096'])
  assert.equal(out.status, 0, out.stderr); assert.ok(Buffer.byteLength(out.stdout) <= 4096); assert.ok(!out.stdout.includes('\uFFFD'))
})
test('recall distinguishes an empty search from missing evidence and rejects raw-path queries as paths', t => {
  const f = fixture(t); f.write('context.md', '# Context\n')
  assert.notEqual(f.run(['recall']).status, 0)
  const out = f.run(['recall', '../other'])
  assert.equal(out.status, 0); assert.match(out.stdout, /no match|no matching/i)
})
test('entry and recall include sanitized policy; heading matches retain nearby denials', t => {
  const f = fixture(t)
  f.write('trust-profile.md', '# Policy\nOnly local models may read source code.\n<private>HIDDEN_POLICY_NOTE</private>')
  f.write('decisions.md', '## Retry approval\nThe sponsor explicitly denied production deployment.\n')
  const entry = f.run(['resume'])
  assert.match(entry.stdout, /Only local models/)
  const policy = f.run(['recall', 'local models'])
  assert.match(policy.stdout, /Only local models/); assert.doesNotMatch(policy.stdout, /HIDDEN_POLICY_NOTE/)
  const decision = f.run(['recall', 'retry approval'])
  assert.match(decision.stdout, /denied production deployment/)
})
test('recall retains recent changes and old constraints when a topic has many matches', t => {
  const f = fixture(t)
  f.write('decisions.md', '- [2026-01-01] retry MUST preserve idempotency. ORIGINAL_CONSTRAINT\n' + Array.from({ length: 50 }, (_, i) => `- retry checkpoint ${i}`).join('\n') + '\n- [2026-09-10] retry approval revoked. LATEST_REVOCATION\n')
  const out = f.run(['recall', 'retry'])
  assert.equal(out.status, 0)
  assert.match(out.stdout, /ORIGINAL_CONSTRAINT/); assert.match(out.stdout, /LATEST_REVOCATION/)
  assert.match(out.stdout, /of 52 matching/)
})
test('recall gives every matching file a turn before taking second excerpts', () => {
  const { recallSections } = require('../bin/lib/context')
  const files = ['brief.md', 'context.md', 'decisions.md', 'delivery.md', 'risks.md', 'success.md', 'trust-profile.md']
  const result = recallSections(files.map(file => ({ file, text: 'deployment first\ndeployment second' })), 'deployment')
  for (const file of files) assert.ok(result.sections.some(s => s.startsWith(file + ':')), file)
})

test('section budget includes truncation markers even with more sections than fit', () => {
  const { boundedSections } = require('../bin/lib/context')
  const out = boundedSections(Array.from({ length: 100 }, () => '客户🙂'.repeat(1000)), 4096)
  assert.ok(Buffer.byteLength(out) <= 4096)
  assert.doesNotMatch(out, /\uFFFD/)
  assert.match(out, /truncated/)
  assert.match(out, /CONTEXT: selected excerpts/)
})

test('fat history cannot displace policy, named signer or the latest sourced decisions at entry', t => {
  const f = fixture(t)
  f.write('trust-profile.md', '# Policy\nLOCAL_MODELS_ONLY: source code stays local.\n' + 'Policy detail '.repeat(10000))
  f.write('success.md', '# Success\n**Stakeholder who signs off:** Mara Chen\n**Done when:** replay returns zero duplicates.\n')
  f.write('context.md', '# Context\n**Phase:** land\n## Next action\nReview replay\n' + Array.from({ length: 1000 }, (_, i) => `Transcript history line ${i}`).join('\n'))
  f.write('decisions.md', Array.from({ length: 1000 }, (_, i) => `- [2026-01-01] Historical choice ${i} [source: meeting:old-${i}]`).join('\n') + '\n- [2026-09-10] Retain replay [source: meeting:recent-a]\n- [2026-09-11] Withdraw release [source: meeting:recent-b]\n')
  const out = f.run(['resume'])
  assert.equal(out.status, 0, out.stderr)
  assert.ok(Buffer.byteLength(out.stdout) <= 16384)
  assert.ok(out.stdout.startsWith(`ENGAGEMENT: ${f.eng}\n\nCLIENT POLICY - trust-profile.md`))
  for (const value of ['LOCAL_MODELS_ONLY', 'Mara Chen', 'meeting:recent-a', 'meeting:recent-b']) assert.ok(out.stdout.includes(value), value)
  assert.doesNotMatch(out.stdout, /Transcript history line 500/)
  assert.match(out.stdout, /truncated|omitted/)
})


test('sections that fit retain complete uneven content including separators and footer', () => {
  const { boundedSections } = require('../bin/lib/context')
  const sections = ['RECORD\n' + '客户🙂'.repeat(180) + '\nENGAGEMENT: fictional-client', '', 'CURRENT ACTION: confirm Tuesday', 'SIGNER: Priya Shah']
  const complete = boundedSections(sections, 65536)
  const bytes = Buffer.byteLength(complete)
  assert.ok(bytes < 4096)
  assert.equal(boundedSections(sections, 4096), complete)
  assert.equal(boundedSections(sections, bytes), complete)
  const clipped = boundedSections(sections, bytes - 1)
  assert.ok(Buffer.byteLength(clipped) <= bytes - 1)
  assert.match(clipped, /Excerpt truncated/)
  assert.doesNotMatch(clipped, /\uFFFD/)
})

test('compact resume preserves a complete fitting packet and still masks private content', t => {
  const f = fixture(t)
  f.write('context.md', '# Context\n**Phase:** land\n## Next action\nConfirm Tuesday replay\n<private>PRIVATE_PACKET_SENTINEL</private>\n')
  f.write('success.md', '# Success\n**Done when:** Replay events; observe exactly one dispatch per ID.\n**Stakeholder who signs off:** Priya Shah [source: meeting:scope]\n')
  f.write('decisions.md', '- [2026-09-10] Keep CSV import [source: meeting:scope]\n')
  const full = f.run(['resume', '--max-bytes', '65536'])
  const compact = f.run(['resume', '--max-bytes', '4096'])
  assert.equal(full.status, 0, full.stderr)
  assert.equal(compact.status, 0, compact.stderr)
  assert.ok(Buffer.byteLength(full.stdout) <= 4096)
  assert.equal(compact.stdout, full.stdout)
  for (const value of [f.eng, 'Keep CSV import', 'Priya Shah', 'Confirm Tuesday replay']) assert.ok(compact.stdout.includes(value), value)
  assert.doesNotMatch(compact.stdout, /Excerpt truncated|PRIVATE_PACKET_SENTINEL/)
})


test('populated compact entry keeps identity, policy and goals outside long triage', t => {
  const f = fixture(t)
  f.write('trust-profile.md', '# Policy\nRead-only until customer approves writes.\n' + 'Policy detail '.repeat(800))
  f.write('success.md', '# Success\n**Stakeholder who signs off:** Mara Chen\n**Done when:** replay produces no duplicates.\n')
  f.write('context.md', '# Context\n**Phase:** land\n## Next action\nReview replay\n' + 'History '.repeat(2000))
  f.write('decisions.md', Array.from({ length: 8 }, (_, i) => `- [2026-09-10] Decision ${i} ${'detail '.repeat(80)} [source: meeting:${i}]`).join('\n'))
  for (const budget of ['4096', '16384']) {
    const out = f.run(['resume', '--max-bytes', budget])
    assert.equal(out.status, 0, out.stderr)
    assert.ok(Buffer.byteLength(out.stdout) <= Number(budget))
    for (const value of [`ENGAGEMENT: ${f.eng}`, 'Read-only until customer approves writes', 'Mara Chen', 'Review replay']) assert.ok(out.stdout.includes(value), value)
    assert.match(out.stdout, /truncated/)
  }
})
