const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const cli = path.resolve(__dirname, '../bin/fde.js')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-personal-'))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const root = path.join(dir, 'clients'), env = { ...process.env, HOME: dir, FDEOPS_ENGAGEMENT: '', FDEOS_ENGAGEMENT: '', FDEOPS_ENGAGEMENTS_ROOT: root }
  const run = args => spawnSync(process.execPath, [cli, ...args], { cwd: dir, env, encoding: 'utf8', timeout: 15000 })
  const terms = path.join(dir, 'terms.txt')
  const save = (work = 'single', start = 'daily', masking = 'standard', file) => run(['setup', '--work', work, '--start', start, '--masking', masking, ...(file ? ['--terms-file', file] : []), '--save'])
  return { dir, root, env, run, terms, save }
}
test('personal setup asks three human questions and changes the initial guidance', t => {
  const f = fixture(t), prompt = f.run(['setup'])
  assert.equal((prompt.stdout.match(/^\d\. /gm) || []).length, 3)
  assert.match(prompt.stdout, /How do you work/)
  assert.doesNotMatch(prompt.stdout, /approved provider|16 KiB/)
  for (const [work, start, action] of [['single', 'new', 'land'], ['multiple', 'daily', 'triage'], ['team', 'takeover', 'audit']]) {
    assert.equal(f.save(work, start).status, 0)
    const info = JSON.parse(f.run(['setup', '--show']).stdout)
    assert.equal(info.work, work); assert.equal(info.start, start)
    assert.match(info.nextStep, new RegExp(action))
    assert.equal(info.view, work === 'multiple' ? 'portfolio' : 'current')
  }
})
test('custom terms stay local, mask context consistently, and restore on confirmed apply', t => {
  const f = fixture(t)
  fs.writeFileSync(f.terms, 'Mara Chen\nAtlas (EU)\n')
  assert.equal(f.save('multiple', 'takeover', 'custom', f.terms).status, 0)
  const info = f.run(['setup', '--show'])
  assert.equal(JSON.parse(info.stdout).termCount, 2)
  assert.doesNotMatch(info.stdout, /Mara Chen|Atlas \(EU\)/)
  assert.equal(f.run(['resume', '--init', 'client-one']).status, 0)
  const notes = path.join(f.dir, 'notes.md')
  fs.writeFileSync(notes, 'decision: Mara Chen will review Atlas (EU). [source: meeting 2026-09-11]\n')
  const preview = f.run(['debrief', '--smart', notes])
  assert.equal(preview.status, 0, preview.stderr)
  const pending = path.join(f.root, 'client-one/.fde/.debrief-propose')
  assert.doesNotMatch(preview.stdout + fs.readFileSync(pending, 'utf8'), /Mara Chen|Atlas \(EU\)/)
  assert.match(preview.stdout, /\[\[term:[a-f0-9]{16}\]\]/)
  assert.equal(f.run(['debrief', '--apply']).status, 0)
  assert.match(fs.readFileSync(path.join(f.root, 'client-one/.fde/decisions.md'), 'utf8'), /Mara Chen will review Atlas \(EU\)/)
  assert.doesNotMatch(f.run(['resume']).stdout, /Mara Chen|Atlas \(EU\)/)
  assert.match(f.run(['resume']).stdout, /Starting help: takeover/)
})
test('custom literals are case insensitive, longest first, and cannot corrupt existing aliases', t => {
  const f = fixture(t)
  fs.writeFileSync(f.terms, 'Mara\nMara Chen\nA+B (EU)\nemail\nterm\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  const m = require('../bin/lib/masking').createMasking(f.root)
  const raw = 'MARA CHEN met A+B (EU). Marathon remains visible. a@example.com'
  const masked = m.mask(raw)
  assert.doesNotMatch(masked, /MARA CHEN|A\+B \(EU\)|a@example.com/)
  assert.match(masked, /Marathon/)
  assert.equal(m.mask(masked), masked)
  assert.equal(m.restore(masked), raw)
})
test('technical edits preserve personal choices and protected terms; old settings still work', t => {
  const f = fixture(t)
  assert.equal(f.run(['setup', '--view', 'current', '--context', 'compact', '--privacy', 'reports', '--save']).status, 0)
  assert.equal(f.save('single', 'new').status, 0)
  let info = JSON.parse(f.run(['setup', '--show']).stdout)
  assert.equal(info.context, 'compact'); assert.equal(info.privacy, 'reports')
  fs.writeFileSync(f.terms, 'Mara Chen\n')
  assert.equal(f.save('single', 'new', 'custom', f.terms).status, 0)
  assert.equal(f.run(['setup', '--view', 'portfolio', '--context', 'standard', '--privacy', 'agent', '--save']).status, 0)
  info = JSON.parse(f.run(['setup', '--show']).stdout)
  assert.equal(info.masking, 'custom'); assert.equal(info.termCount, 1); assert.equal(info.start, 'new')
  assert.equal(f.save('single', 'takeover', 'custom').status, 0)
  assert.equal(JSON.parse(f.run(['setup', '--show']).stdout).view, 'portfolio')
  assert.equal(f.save('single', 'daily', 'standard').status, 0)
  assert.equal(f.save('single', 'daily', 'custom').status, 0, 'saved terms can be reused')
})
test('invalid custom terms and unsafe files never replace working settings', t => {
  const f = fixture(t); assert.equal(f.save().status, 0)
  const before = fs.readFileSync(path.join(f.root, '.preferences.json'))
  for (const body of ['', 'x\n', '[[term:0123456789abcdef]]\n', 'a'.repeat(129)]) {
    fs.writeFileSync(f.terms, body)
    assert.notEqual(f.save('single', 'daily', 'custom', f.terms).status, 0)
    assert.deepEqual(fs.readFileSync(path.join(f.root, '.preferences.json')), before)
  }
  fs.unlinkSync(f.terms); fs.symlinkSync(path.join(f.root, '.preferences.json'), f.terms)
  assert.notEqual(f.save('single', 'daily', 'custom', f.terms).status, 0)
})
test('bad custom settings fail closed for model-facing outputs', t => {
  const f = fixture(t); fs.writeFileSync(f.terms, 'Mara Chen\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  const m = require('../bin/lib/masking').createMasking(f.root)
  assert.doesNotMatch(m.mask('Mara Chen'), /Mara Chen/)
  fs.writeFileSync(path.join(f.root, '.preferences.json'), '{broken')
  assert.throws(() => m.mask('Mara Chen'))
  const result = f.run(['recall', 'Mara Chen'])
  assert.notEqual(result.status, 0)
  assert.doesNotMatch(result.stdout + result.stderr, /Mara Chen/)
})
test('MCP masks quoted custom terms without changing transport or payload keys', t => {
  const f = fixture(t)
  fs.writeFileSync(f.terms, 'Atlas "East"\nerror\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  const server = path.resolve(__dirname, '../mcp/fdeops-ingest/server.js')
  const request = { jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'Atlas "East"', arguments: {} } }
  const result = spawnSync(process.execPath, [server], { cwd: f.dir, env: f.env, input: JSON.stringify(request) + '\n', encoding: 'utf8', timeout: 5000 })
  assert.equal(result.status, 0, result.stderr)
  const response = JSON.parse(result.stdout)
  assert.equal(response.jsonrpc, '2.0'); assert.equal(response.id, 1)
  assert.doesNotMatch(JSON.stringify(response), /Atlas/)
  assert.match(JSON.stringify(response), /term:/)
})
test('setup inspection cannot expose the custom list or corrupt JSON when terms match metadata', t => {
  const f = fixture(t)
  fs.writeFileSync(f.terms, 'work\nconfigured\nsingle\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  const show = JSON.parse(f.run(['setup', '--show']).stdout)
  assert.equal(show.configured, true); assert.equal(show.work, 'single')
  assert.equal(show.termCount, 3); assert.equal(show.terms, undefined)
})

test('quoted and backslash custom terms are masked before command diagnostics are serialized', t => {
  const f = fixture(t), term = 'Mara "Secret" Chen', other = 'Atlas\\East'
  fs.writeFileSync(f.terms, term + '\n' + other + '\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  assert.equal(f.run(['resume', '--init', 'client']).status, 0)
  for (const text of [term, other]) {
    for (const args of [['redact', text], ['log', 'risk', '--retire', text]]) {
      const out = f.run(args)
      assert.doesNotMatch(out.stdout + out.stderr, /Mara|Secret|Atlas/)
    }
  }
})
test('delivery-history lookups treat shell characters as record text', t => {
  const f = fixture(t)
  assert.equal(f.run(['resume', '--init', 'client']).status, 0)
  const marker = path.join(f.dir, 'must-not-exist')
  assert.equal(f.run(['log', 'delivery', 'Tested slice $(touch ' + marker + ')']).status, 0)
  assert.equal(f.run(['resume']).status, 0)
  assert.equal(fs.existsSync(marker), false)
})
test('custom terms are masked before HTML search metadata encoding and preserve acceptance', t => {
  const f = fixture(t), term = 'Mara "Secret" Chen'
  fs.writeFileSync(f.terms, term + '\npending\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  assert.equal(f.run(['setup', '--view', 'current', '--context', 'standard', '--privacy', 'reports', '--save']).status, 0)
  assert.equal(f.run(['resume', '--init', 'client']).status, 0)
  const eng = path.join(f.root, 'client/.fde')
  fs.writeFileSync(path.join(eng, 'context.md'), '# Context\n## Next action\nAsk ' + term + ' for the review.\n')
  fs.writeFileSync(path.join(eng, 'delivery.md'), '# Delivery\n## Value ledger\n| Slice | Promised | Measured | Accepted by | Evidence |\n|---|---|---|---|---|\n| Alert | 20ms | 10ms | pending | [source: meeting 2026-09-11] |\n')
  const result = f.run(['dashboard'])
  assert.equal(result.status, 0, result.stderr)
  const html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.doesNotMatch(html, /Mara|Secret|Acceptance recorded/)
  assert.match(html, /CLAIM/)
  assert.match(fs.readFileSync(path.join(eng, 'context.md'), 'utf8'), /Mara/)
})
test('private preferences are excluded when accidentally staged in the engagement ledger', t => {
  const f = fixture(t)
  assert.equal(f.run(['resume', '--init', 'client']).status, 0)
  const eng = path.join(f.root, 'client/.fde')
  fs.writeFileSync(path.join(eng, '.preferences.json'), JSON.stringify({ view: 'current', context: 'standard', privacy: 'agent' }))
  spawnSync('git', ['add', '-f', '.preferences.json'], { cwd: eng })
  const result = f.run(['log', 'decision', 'Keep the approved scope.'])
  const tracked = spawnSync('git', ['ls-files'], { cwd: eng, encoding: 'utf8' }).stdout
  assert.doesNotMatch(tracked, /preferences/)
})

test('derived metric widgets cannot reconstruct a masked phrase', t => {
  const f = fixture(t), term = 'Project SecretAtlas 12% to 20%'
  fs.writeFileSync(f.terms, term + '\n')
  assert.equal(f.save('single', 'daily', 'custom', f.terms).status, 0)
  assert.equal(f.run(['setup', '--view', 'current', '--context', 'standard', '--privacy', 'reports', '--save']).status, 0)
  assert.equal(f.run(['resume', '--init', 'client']).status, 0)
  fs.writeFileSync(path.join(f.root, 'client/.fde/delivery.md'), '# Delivery\n' + term + '\n')
  assert.equal(f.run(['dashboard']).status, 0)
  const html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.doesNotMatch(html, /SecretAtlas|12%|20%/)
})
