const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const cli = path.resolve(__dirname, '../bin/fde.js')
const installer = path.resolve(__dirname, '../bin/install.js')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-setup-'))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const root = path.join(dir, 'clients')
  const env = { ...process.env, HOME: dir, USERPROFILE: dir, FDEOPS_ENGAGEMENT: '', FDEOS_ENGAGEMENT: '', FDEOPS_ENGAGEMENTS_ROOT: root }
  const run = (args, executable = cli) => spawnSync(process.execPath, [executable, ...args], { cwd: dir, env, encoding: 'utf8', timeout: 15000 })
  const save = (view = 'current', context = 'standard', privacy = 'agent') => run(['setup', '--view', view, '--context', context, '--privacy', privacy, '--save'])
  return { dir, root, env, run, save }
}
test('setup previews exactly three questions without writes or waiting on noninteractive stdin', t => {
  const f = fixture(t), out = f.run(['setup'])
  assert.equal(out.status, 0, out.stderr)
  assert.equal((out.stdout.match(/^\d\. /gm) || []).length, 3)
  assert.match(out.stdout, /AI-provider settings are unchanged/)
  assert.equal(fs.existsSync(f.root), false)
  assert.equal(JSON.parse(f.run(['setup', '--show']).stdout).configured, false)
  assert.equal(fs.existsSync(f.root), false)
})
test('explicit answers persist, can be changed, and init asks only while setup is missing', t => {
  const f = fixture(t)
  assert.match(f.run(['resume', '--init', 'atlas']).stdout, /run fde setup once/)
  assert.equal(f.save('portfolio', 'compact', 'reports').status, 0)
  assert.deepEqual(JSON.parse(f.run(['setup', '--show']).stdout), { configured: true, view: 'portfolio', context: 'compact', privacy: 'reports' })
  assert.doesNotMatch(f.run(['resume', '--init', 'beacon']).stdout, /run fde setup once/)
  assert.equal(f.save().status, 0)
  assert.equal(JSON.parse(f.run(['setup', '--show']).stdout).view, 'current')
  if (process.platform !== 'win32') assert.equal(fs.statSync(path.join(f.root, '.preferences.json')).mode & 0o777, 0o600)
})
test('invalid, incomplete, duplicate and unknown choices cannot overwrite settings', t => {
  const f = fixture(t); assert.equal(f.save().status, 0)
  const before = fs.readFileSync(path.join(f.root, '.preferences.json'))
  for (const args of [
    ['--save'], ['--view', 'portfolio', '--save'],
    ['--view', 'bad', '--context', 'standard', '--privacy', 'agent', '--save'],
    ['--view', 'current', '--context', 'standard', '--privacy', 'agent', '--view', 'portfolio', '--save'],
    ['--view', 'current', '--context', 'standard', '--privacy', 'agent', '--other', 'x', '--save'],
  ]) assert.notEqual(f.run(['setup', ...args]).status, 0)
  assert.deepEqual(fs.readFileSync(path.join(f.root, '.preferences.json')), before)
})
test('symlinked and corrupt settings fail without falling back to less restrictive defaults', t => {
  const f = fixture(t); assert.equal(f.save().status, 0)
  const file = path.join(f.root, '.preferences.json'), outside = path.join(f.dir, 'outside')
  fs.renameSync(file, outside); fs.symlinkSync(outside, file)
  const before = fs.readFileSync(outside)
  assert.notEqual(f.save().status, 0)
  assert.notEqual(f.run(['setup', '--show']).status, 0)
  assert.notEqual(f.run(['dashboard']).status, 0)
  assert.deepEqual(fs.readFileSync(outside), before)
  fs.unlinkSync(file); fs.writeFileSync(file, '{broken')
  assert.notEqual(f.run(['resume']).status, 0)
  assert.notEqual(f.save().status, 0, 'do not discard potentially protected custom terms when preferences are corrupt')
  assert.equal(fs.readFileSync(file, 'utf8'), '{broken')
})
test('compact setup caps default context; an explicit byte budget still works', t => {
  const f = fixture(t); assert.equal(f.run(['resume', '--init', 'atlas']).status, 0)
  const file = path.join(f.root, 'atlas/.fde/context.md')
  fs.writeFileSync(file, '# Context\n## Next action\n' + 'Review staging evidence for the rollout. '.repeat(1500))
  const original = fs.readFileSync(file)
  assert.equal(f.save('current', 'compact').status, 0)
  const compact = f.run(['resume'])
  assert.equal(compact.status, 0, compact.stderr)
  assert.ok(Buffer.byteLength(compact.stdout) <= 4096)
  const override = f.run(['resume', '--max-bytes', '16384'])
  assert.equal(override.status, 0, override.stderr)
  assert.ok(Buffer.byteLength(override.stdout) > 4096)
  assert.ok(Buffer.byteLength(override.stdout) <= 16384)
  assert.deepEqual(fs.readFileSync(file), original)
})
test('portfolio preference affects reports, never the bound client; current overrides it', t => {
  const f = fixture(t)
  assert.equal(f.run(['resume', '--init', 'atlas']).status, 0)
  assert.equal(f.run(['resume', '--init', 'beacon']).status, 0)
  assert.equal(f.save('portfolio').status, 0)
  assert.match(f.run(['dashboard']).stdout, /2 engagement\(s\) rendered/)
  assert.match(f.run(['dashboard', '--current']).stdout, /1 engagement\(s\) rendered/)
  assert.match(f.run(['status']).stdout, /atlas/)
  assert.doesNotMatch(f.run(['status', '--current']).stdout, /atlas/)
  assert.notEqual(f.run(['dashboard', '--current', '--all']).status, 0)
  assert.match(f.run(['resume', '--bind']).stdout, /beacon/)
})
test('report masking covers source text before clipping, preserves originals, and can be changed', t => {
  const f = fixture(t); assert.equal(f.run(['resume', '--init', 'atlas']).status, 0)
  const file = path.join(f.root, 'atlas/.fde/brief.md')
  const raw = '# Brief\nContact mara@example.com at +1 415 555 0123. <private>HIDDEN_PERSON</private>\n'
  fs.writeFileSync(file, raw)
  assert.equal(f.save('current', 'standard', 'reports').status, 0)
  assert.equal(f.run(['dashboard']).status, 0)
  let html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.doesNotMatch(html, /mara@example.com|415 555 0123|HIDDEN_PERSON/)
  assert.match(html, /\[\[email:/)
  const out = path.join(f.dir, 'vault')
  const result = f.run(['vault', '--current', '--out', out])
  assert.equal(result.status, 0, result.stderr)
  function texts(dir) { return fs.readdirSync(dir, { withFileTypes: true }).map(e => e.isDirectory() ? texts(path.join(dir, e.name)) : fs.readFileSync(path.join(dir, e.name), 'utf8')).join('\n') }
  assert.doesNotMatch(texts(out), /mara@example.com|415 555 0123|HIDDEN_PERSON/)
  assert.equal(fs.readFileSync(file, 'utf8'), raw)
  assert.equal(f.save().status, 0)
  assert.equal(f.run(['dashboard']).status, 0)
  html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.match(html, /mara@example.com/)
  assert.doesNotMatch(html, /HIDDEN_PERSON/)
})
test('npx dispatcher exposes setup and privacy without installing anything', t => {
  const f = fixture(t)
  assert.equal(f.run(['setup', '--show'], installer).status, 0)
  const privacy = f.run(['privacy'], installer)
  assert.equal(privacy.status, 0, privacy.stderr)
  assert.match(privacy.stdout, /masking enabled/)
  assert.equal(fs.existsSync(path.join(f.dir, '.claude')), false)
})

test('masking report identifiers never upgrades an unsigned number or pending contact to accepted', t => {
  const f = fixture(t); assert.equal(f.run(['resume', '--init', 'atlas']).status, 0)
  fs.writeFileSync(path.join(f.root, 'atlas/.fde/delivery.md'), '# Delivery\n\n## Value ledger\n\n| Slice | Type | Promised | Measured | Accepted by | Evidence | Rollback |\n|---|---|---|---|---|---|---|\n| Numeric signer | value | 20ms | 10ms | 123-45-6789 | [source: meeting 2026-09-11] | revert |\n| Pending contact | value | 20ms | 10ms | pending@example.com | [source: meeting 2026-09-11] | revert |\n')
  assert.equal(f.save('current', 'standard', 'reports').status, 0)
  assert.equal(f.run(['dashboard']).status, 0)
  const html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.doesNotMatch(html, /Acceptance recorded|123-45-6789|pending@example.com/)
  assert.equal((html.match(/CLAIM · Awaiting acceptance/g) || []).length, 2)
})

test('report masking covers recognized identifiers in client titles and vault metadata', t => {
  const f = fixture(t); assert.equal(f.run(['resume', '--init', '123-45-6789']).status, 0)
  assert.equal(f.save('current', 'standard', 'reports').status, 0)
  assert.equal(f.run(['dashboard']).status, 0)
  assert.doesNotMatch(fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8'), /123-45-6789/)
  const out = path.join(f.dir, 'vault')
  assert.equal(f.run(['vault', '--out', out]).status, 0)
  function walk(dir) { return fs.readdirSync(dir, { withFileTypes: true }).map(e => e.name + (e.isDirectory() ? walk(path.join(dir, e.name)) : fs.readFileSync(path.join(dir, e.name), 'utf8'))).join('\n') }
  assert.doesNotMatch(walk(out), /123-45-6789/)
})

test('report metric and trust snippets mask whole identifiers before shortening them', t => {
  const f = fixture(t); assert.equal(f.run(['resume', '--init', 'atlas']).status, 0)
  const eng = path.join(f.root, 'atlas/.fde'), credential = 'ghp_' + 'a'.repeat(55)
  fs.writeFileSync(path.join(eng, 'delivery.md'), '# Delivery\nCredential ' + credential + ' 1% -> 2%\n')
  fs.writeFileSync(path.join(eng, 'risks.md'), '# Risks\n## Open\n- ' + 'x'.repeat(65) + ' mara@example.com\n')
  assert.equal(f.save('current', 'standard', 'reports').status, 0)
  assert.equal(f.run(['dashboard']).status, 0)
  const html = fs.readFileSync(path.join(f.root, 'fieldbook-current.html'), 'utf8')
  assert.doesNotMatch(html, /a{20}|mara@example|ghp_/)
  assert.match(html, /1%/)
  assert.match(html, /2%/)
})
